#!/bin/bash -e

args="$@"

db () {
  docker build ${args} -f $1 -t $2:latest ./
}

db thell-rstudio.dockerfile rstudio
db thell-rstudio-pbsi.dockerfile rstudio-pbsi
db cli-gcc-explorer.dockerfile gcc-explorer
db cli-cpp-to-assembly.dockerfile cpp-to-assembly

if [ -d ./lib/eureqa ]; then
	db user-eureqa.dockerfile eureqa
fi